### ISSUE TITLE
Example.docx is missing

### ISSUE THREAD

**Issue by canerakin111** [geeks-of-data/knowledge-gpt#54]
I assume I am getting the error due to not having the example.docx for the example code below.

https://github.com/geeks-of-data/knowledge-gpt/blob/master/examples/docs_example_saving.ipynb

See attached.
![image](https://user-images.githubusercontent.com/35246326/226432015-f9d49995-d80a-4cb5-a139-b0cfa200faba.png)

**Comment by eren23** [comment]
No I think this it probably because you are trying to use newer features with an older version of the library, (you use 0.0.3b from pypi I guess) but this feature of index_path is only available for newer versions ( not released yet, available in master ) you can either remove index_path argument or you can update it. index_path argument, when is provided allows you to save your embeddings to a directory so next time you use it you don't need to calculate again.

**Comment by eren23** [comment]
> I assume I am getting the error due to not having the example.docx for the example code below.
> 
> https://github.com/geeks-of-data/knowledge-gpt/blob/master/examples/docs_example_saving.ipynb
> 
> See attached. ![image](https://user-images.githubusercontent.com/35246326/226432015-f9d49995-d80a-4cb5-a139-b0cfa200faba.png)

Hey, install the latest pip version to get the newest version, v0.0.5b is now available on PyPI.
